In [98]:
%run read_data.ipynb
%run read_test.ipynb
%run model_fixed_point.ipynb
%run model.ipynb

In [84]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [85]:
def load_para_f(k1,k2,dk1,dk2,db1,db2,b1,b2,fb):
    k1 = k1-k1%(2**fb)
    k2 = k2-k2%(2**fb)
    dk1 = dk1-dk1%(2**fb)
    dk2 = dk2-dk2%(2**fb)
    db1 = db1-db1%(2**fb)
    db2 = db2-db2%(2**fb)
    b1 = -0.00734525
    b2 = -0.05760591
    b1 = b1-b1%(2**fb)
    b2 = b2-b2%(2**fb)
    return (k1,k2,dk1,dk2,db1,db2,b1,b2)

In [86]:
def load_data():
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    if K.image_data_format() == 'channels_first':
        x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
        x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
        input_shape = (1, img_rows, img_cols)
    else:
        x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
        x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
        input_shape = (img_rows, img_cols, 1)

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 255
    x_test /= 255
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)
 
    return (x_test,y_test)

In [2]:
import import_ipynb 
import numpy as np
import keras
from keras.datasets import mnist
from keras import backend as K
from random import randrange


num_classes = 10

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
#print(y_test.shape)
#print(x_test.shape)
#print(y_test.shape[0])
#print(x_test.shape[0])

Using TensorFlow backend.


In [56]:
# access data

#x = pass_x('../test_data/testx3.txt')
#y = pass_y('../test_data/testy3.txt')
k1 = pass_k1()
k2 = pass_k2()
dk1 = pass_dk1()
dk2 = pass_dk2()
db1 = pass_db1()
db2 = pass_db2()
b1 = -0.00734525
b2 = -0.05760591

correct = 0;
test_num = 800
#for i in range(test_num):
 #   if cnn_model(x_test[i],y_test[i],k1,k2,dk1,dk2,db1,db2,b1,b2):
  #      correct = correct + 1

#cnn_model(x_test[0],y_test[0],k1,k2,dk1,dk2,db1,db2,b1,b2)
print('correct number is',correct,'between',test_num,'test case')
print('correct rate is ',correct/test_num)


print('.................')
 

correct number is 0 between 800 test case
correct rate is  0.0
.................


In [9]:
# convert floating point to fixed-point

fb = -8

k1 = k1-k1%(2**fb)
k2 = k2-k2%(2**fb)
dk1 = dk1-dk1%(2**fb)
dk2 = dk2-dk2%(2**fb)
db1 = db1-db1%(2**fb)
db2 = db2-db2%(2**fb)
b1 = -0.00734525
b2 = -0.05760591
b1 = b1-b1%(2**fb)
b2 = b2-b2%(2**fb)

correct = 0;
test_num = 800
for i in range(test_num):
    if cnn_model_f(x_test[i],y_test[i],k1,k2,dk1,dk2,db1,db2,b1,b2,0,fb):
        correct = correct + 1
 
print('correct number is',correct,'between',test_num,'test case')
print('correct rate is ',correct/test_num)

correct number is 779 between 800 test case
correct rate is  0.97375


In [87]:
# convert floating point to fixed-point

fb = -8


correct = 0;
test_num = 250

for FB in range(fb,0,1):
    (K1,K2,DK1,DK2,DB1,DB2,B1,B2) = load_para_f(k1,k2,dk1,dk2,db1,db2,b1,b2,FB)
    (X,Y) = load_data()
    for i in range(test_num):
        X[i] = X[i]-X[i]%(2**FB)
        if cnn_model_f(X[i],Y[i],K1,K2,dk1,dk2,db1,db2,B1,B2,i,FB):
            correct = correct + 1
    
    print('bit after int is: ',-FB,'bits')
    print('correct number is',correct,'between',test_num,'test case')
    print('correct rate is ',correct/test_num)
    print('------------------------------')
    correct = 0
 
#print('correct number is',correct,'between',test_num,'test case')
#print('correct rate is ',correct/test_num)

bit after int is:  8 bits
correct number is 247 between 250 test case
correct rate is  0.988
------------------------------
bit after int is:  7 bits
correct number is 247 between 250 test case
correct rate is  0.988
------------------------------
bit after int is:  6 bits
correct number is 246 between 250 test case
correct rate is  0.984
------------------------------
bit after int is:  5 bits
correct number is 246 between 250 test case
correct rate is  0.984
------------------------------
bit after int is:  4 bits
correct number is 245 between 250 test case
correct rate is  0.98
------------------------------
bit after int is:  3 bits
correct number is 245 between 250 test case
correct rate is  0.98
------------------------------
bit after int is:  2 bits
correct number is 221 between 250 test case
correct rate is  0.884
------------------------------
bit after int is:  1 bits
correct number is 42 between 250 test case
correct rate is  0.168
------------------------------


In [99]:
correct = 0;
(X,Y) = load_data()
test_num = 250
for i in range(test_num):
    if cnn_model(X[i],Y[i],k1,k2,dk1,dk2,db1,db2,b1,b2):
        correct = correct + 1
print(correct/test_num)

0.988


In [47]:
(X,Y) = load_data()
for i in range(28):
    for j in range(28):
        if X[0][i][j]!=0:
            print(X[0][i][j],end=' ')
print('-------')
fb=-10
index = 3
X[index] = X[index]-X[index]%(2**fb)
for i in range(28):
    for j in range(28):
        if X[index][i][j]!=0:
            print(X[index][i][j],end=' ')

print('------')
print('-------')
if cnn_model_f(X[index],Y[index],k1,k2,dk1,dk2,db1,db2,b1,b2,0,fb):
    print('a')
else :
    print('b')
print(Y[index])

[0.32941177] [0.7254902] [0.62352943] [0.5921569] [0.23529412] [0.14117648] [0.87058824] [0.99607843] [0.99607843] [0.99607843] [0.99607843] [0.94509804] [0.7764706] [0.7764706] [0.7764706] [0.7764706] [0.7764706] [0.7764706] [0.7764706] [0.7764706] [0.6666667] [0.20392157] [0.2627451] [0.44705883] [0.28235295] [0.44705883] [0.6392157] [0.8901961] [0.99607843] [0.88235295] [0.99607843] [0.99607843] [0.99607843] [0.98039216] [0.8980392] [0.99607843] [0.99607843] [0.54901963] [0.06666667] [0.25882354] [0.05490196] [0.2627451] [0.2627451] [0.2627451] [0.23137255] [0.08235294] [0.9254902] [0.99607843] [0.41568628] [0.3254902] [0.99215686] [0.81960785] [0.07058824] [0.08627451] [0.9137255] [1.] [0.3254902] [0.5058824] [0.99607843] [0.93333334] [0.17254902] [0.23137255] [0.9764706] [0.99607843] [0.24313726] [0.52156866] [0.99607843] [0.73333335] [0.01960784] [0.03529412] [0.8039216] [0.972549] [0.22745098] [0.49411765] [0.99607843] [0.7137255] [0.29411766] [0.9843137] [0.9411765] [0.22352941

In [82]:
print(k1)

[[ 0.44204316  0.20372748  0.32394782]
 [ 0.08491429  0.66045576  0.35053986]
 [ 0.5027545   0.50884897 -0.13011555]]
