In [1]:
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(2, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
 
model.add(MaxPooling2D(pool_size=(2, 2)))
 
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Using TensorFlow backend.


x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 22s 366us/step - loss: 0.5080 - acc: 0.8438 - val_loss: 0.2014 - val_acc: 0.9392
Epoch 2/12
60000/60000 [==============================] - 18s 298us/step - loss: 0.2709 - acc: 0.9188 - val_loss: 0.1551 - val_acc: 0.9539
Epoch 3/12
60000/60000 [==============================] - 19s 311us/step - loss: 0.2300 - acc: 0.9306 - val_loss: 0.1359 - val_acc: 0.9584
Epoch 4/12
60000/60000 [==============================] - 18s 303us/step - loss: 0.2108 - acc: 0.9371 - val_loss: 0.1263 - val_acc: 0.9612
Epoch 5/12
60000/60000 [==============================] - 18s 305us/step - loss: 0.193

In [21]:
print('kernel')
print(model.layers[0].get_weights()[0])
#print(model.layers[0].get_weights()[0][1])
print('bias')
print(model.layers[0].get_weights()[1])

kernel
[[[[ 0.70211357 -0.4442712 ]]

  [[ 0.8564747   0.5860631 ]]

  [[ 0.5609598   0.45131308]]]


 [[[-0.35779247  0.7455675 ]]

  [[ 0.55761576  0.84799486]]

  [[ 0.59541386  0.17450665]]]


 [[[-0.8976044   0.35378945]]

  [[-0.69156784  0.63801837]]

  [[ 0.37172773 -0.46260032]]]]
bias
[-0.04460439 -0.19052994]


In [11]:
for lay in model.layers:
    print(lay.name)
    print(lay.get_weights())

conv2d_1
[array([[[[ 0.70211357, -0.4442712 ]],

        [[ 0.8564747 ,  0.5860631 ]],

        [[ 0.5609598 ,  0.45131308]]],


       [[[-0.35779247,  0.7455675 ]],

        [[ 0.55761576,  0.84799486]],

        [[ 0.59541386,  0.17450665]]],


       [[[-0.8976044 ,  0.35378945]],

        [[-0.69156784,  0.63801837]],

        [[ 0.37172773, -0.46260032]]]], dtype=float32), array([-0.04460439, -0.19052994], dtype=float32)]
max_pooling2d_1
[]
flatten_1
[]
dense_1
[array([[ 0.07912487,  0.11261863,  0.01695131, ...,  0.09061931,
        -0.01822531,  0.05584265],
       [ 0.10144848, -0.08696575, -0.01952044, ..., -0.0795992 ,
         0.03803489, -0.01704563],
       [-0.01178386, -0.08163375, -0.07249153, ...,  0.10846979,
        -0.0388036 , -0.04737002],
       ...,
       [ 0.07237762,  0.00306423,  0.12174901, ...,  0.00974925,
        -0.04203131, -0.03768809],
       [ 0.02823075,  0.02040139, -0.08578642, ..., -0.05624649,
        -0.01073481, -0.08779221],
       [ 0.0015