In [2]:
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(2, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
 
model.add(MaxPooling2D(pool_size=(2, 2)))
 
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Using TensorFlow backend.


x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 21s 352us/step - loss: 0.5257 - acc: 0.8374 - val_loss: 0.2157 - val_acc: 0.9352
Epoch 2/12
60000/60000 [==============================] - 21s 355us/step - loss: 0.2783 - acc: 0.9161 - val_loss: 0.1673 - val_acc: 0.9509
Epoch 3/12
60000/60000 [==============================] - 19s 315us/step - loss: 0.2419 - acc: 0.9276 - val_loss: 0.1466 - val_acc: 0.9553
Epoch 4/12
60000/60000 [==============================] - 19s 309us/step - loss: 0.2156 - acc: 0.9351 - val_loss: 0.1298 - val_acc: 0.9609
Epoch 5/12
60000/60000 [==============================] - 19s 314us/step - loss: 0.200

In [21]:
print('kernel')
print(model.layers[0].get_weights()[0])
#print(model.layers[0].get_weights()[0][1])
print('bias')
print(model.layers[0].get_weights()[1])

kernel
[[[[ 0.70211357 -0.4442712 ]]

  [[ 0.8564747   0.5860631 ]]

  [[ 0.5609598   0.45131308]]]


 [[[-0.35779247  0.7455675 ]]

  [[ 0.55761576  0.84799486]]

  [[ 0.59541386  0.17450665]]]


 [[[-0.8976044   0.35378945]]

  [[-0.69156784  0.63801837]]

  [[ 0.37172773 -0.46260032]]]]
bias
[-0.04460439 -0.19052994]


In [16]:
print('kernel shape:',model.layers[0].get_weights()[0].shape)
print('bias shape:',model.layers[0].get_weights()[1].shape)

kernel shape: (3, 3, 1, 2)
bias shape: (2,)


In [15]:
# write trained data into file

k1_file = open('kernel1.txt','w')
k2_file = open('kernel2.txt','w')

for i in range(3):
    for j in range(3):
        k1_file.write(str(model.layers[0].get_weights()[0][i][j][0][0])+'\n')
        k2_file.write(str(model.layers[0].get_weights()[0][i][j][0][1])+'\n')
        
k1_file.close()
k2_file.close()

b1_file = open('bias1.txt','w')
b2_file = open('bias2.txt','w')

b1_file.write(str(model.layers[0].get_weights()[1][0]))
b2_file.write(str(model.layers[0].get_weights()[1][1]))
b1_file.close()
b2_file.close()

In [17]:
for lay in model.layers:
    print(lay.name)
    print(lay.get_weights())

conv2d_1
[array([[[[-0.46026877,  0.40871835]],

        [[ 0.34092835,  0.20461129]],

        [[ 0.37125877,  0.3977643 ]]],


       [[[-0.9940661 ,  0.83744013]],

        [[ 0.04112912,  0.95963717]],

        [[ 0.83141106,  0.27900922]]],


       [[[-0.6351352 , -0.41077206]],

        [[ 0.21337418, -0.18322632]],

        [[ 0.93388295,  0.53992754]]]], dtype=float32), array([-0.39380574,  0.01279862], dtype=float32)]
max_pooling2d_1
[]
flatten_1
[]
dense_1
[array([[ 0.0833168 ,  0.07500234, -0.09870519, ...,  0.04700266,
        -0.00565294,  0.05313679],
       [ 0.04648725, -0.07747693, -0.03979786, ..., -0.0909694 ,
        -0.04117072, -0.02105643],
       [-0.03982475, -0.0625999 ,  0.0540235 , ..., -0.08261127,
        -0.0902487 ,  0.02332269],
       ...,
       [-0.11953068,  0.06431189, -0.04715253, ...,  0.03516444,
        -0.04429092, -0.12911092],
       [-0.10934352,  0.02087899,  0.0626666 , ...,  0.02085487,
         0.05397647, -0.08841191],
       [-0.0806

In [3]:
print('dense layer1 kernel shape:',model.layers[3].get_weights()[0].shape)
print('dense layer1 bias shape:',model.layers[3].get_weights()[1].shape)
print('dense layer2 kernel shape:',model.layers[5].get_weights()[0].shape)
print('dense layer2 bias shape:',model.layers[5].get_weights()[1].shape)

dense layer1 kernel shape: (338, 128)
dense layer1 bias shape: (128,)
dense layer2 kernel shape: (128, 10)
dense layer2 bias shape: (10,)


In [27]:
# write dense kernel into file

dk1_f = open('dk1.txt','w')
for i in range(338):
    for j in range(128):
        dk1_f.write(str(model.layers[3].get_weights()[0][i][j])+'\n')
dk1_f.close()

dk2_f = open('dk2.txt','w')
for i in range(128):
    for j in range(10):
        dk2_f.write(str(model.layers[5].get_weights()[0][i][j])+'\n')
dk2_f.close()

db1_f = open('db1.txt','w')
for i in range(128):
    db1_f.write(str(model.layers[3].get_weights()[1][i])+'\n')
db1_f.close()

db2_f = open('db2.txt','w')
for i in range(10):
    db2_f.write(str(model.layers[5].get_weights()[1][i])+'\n')
db2_f.close()

In [1]:
# write test_data into file
print(x_test.shape)
print(y_test.shape)
num = 3
for i in range(num):
    fx = open('test_data/testx'+str(i)+'.txt','w')
    for j in range(28):
        for k in range(28):
            fx.write(str(x_test[i][j][k][0])+'\n')
    fx.close()
 
for i in range(num):
    fy = open('test_data/testy'+str(i)+'.txt','w')
    for j in range(10):
        fy.write(str(x_test[i][j])+'\n')
    fy.close()
    
print('write finish!')

NameError: name 'x_test' is not defined