In [19]:
import numpy as np


'''
a = np.array([1,2,3])
print(a)
a = np.append(a,5)
print(a)
b = np.array([[3,3,3,3]])
a = np.append([a],b,axis=0)
print(a)

[1 2 3]
[1 2 3 5]
[[1 2 3 5]
 [3 3 3 3]]

'''

# try to read db2 and store in array 
# success!!
db2 = np.array([])
with open('db2.txt') as f:
   for line in f:
       db2 = np.append(db2,float(line))
       if 'str' in line:
          break
# print(db2)

# try to read dk2 and store in array

 

[ 0.07903159  0.04067429 -0.2429174   0.10326468 -0.2115504  -0.30638444
 -0.18215817 -0.1126826   0.3312668   0.27184293]
