In [4]:
import numpy as np


'''
a = np.array([1,2,3])
print(a)
a = np.append(a,5)
print(a)
b = np.array([[3,3,3,3]])
a = np.append([a],b,axis=0)
print(a)

[1 2 3]
[1 2 3 5]
[[1 2 3 5]
 [3 3 3 3]]

'''

# try to read db2 and store in array 
# success!!
db2 = np.array([])
with open('db2.txt') as f:
    for line in f:
        db2 = np.append(db2,float(line))
        if 'str' in line:
            break
print('db2 shape: ',db2.shape)
print('array: \n',db2)
print()
# try to read dk2 and store in array
# success
dk1 = np.empty((0,128),float)
row = np.array([])
dk1f = open('dk1.txt','r')

line = dk1f.readline()
while line:
    for i in range(128): 
        row = np.append(row,float(line))
        line = dk1f.readline()
    dk1 = np.append(dk1,np.expand_dims(row, axis=0),axis=0)
    row = np.array([])
dk1f.close()
print('dk1.shape is: ',dk1.shape)
print('array: \n',dk1)

db2 shape:  (10,)
array: 
 [ 0.07903159  0.04067429 -0.2429174   0.10326468 -0.2115504  -0.30638444
 -0.18215817 -0.1126826   0.3312668   0.27184293]

dk1.shape is:  (338, 128)
array: 
 [[ 0.0833168   0.07500234 -0.09870519 ...  0.04700266 -0.00565294
   0.05313679]
 [ 0.04648725 -0.07747693 -0.03979787 ... -0.0909694  -0.04117072
  -0.02105643]
 [-0.03982475 -0.0625999   0.0540235  ... -0.08261127 -0.0902487
   0.02332269]
 ...
 [-0.11953068  0.06431189 -0.04715253 ...  0.03516444 -0.04429092
  -0.12911092]
 [-0.10934352  0.020879    0.0626666  ...  0.02085487  0.05397647
  -0.08841191]
 [-0.08061297 -0.09311254 -0.10230023 ... -0.10269619  0.0349522
  -0.09535502]]
